RGBLIGHT_ENABLE = false

OLED_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
UNICODE_ENABLE = yes
OS_DETECTION_ENABLE = yes
RAW_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

SRC += lib/naginata/naginata_v15.c
